apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"load-generator","research":"autoscaler-baseline"},"name":"load-generator","namespace":"research-workload"},"spec":{"maxReplicas":10,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":80,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"load-generator"}}}
  creationTimestamp: "2026-06-26T15:26:41Z"
  labels:
    app: load-generator
    research: autoscaler-baseline
  name: load-generator
  namespace: research-workload
  resourceVersion: "1782487662480623023"
  uid: 99c2c4e4-e69f-46ec-86ae-c7da702085f7
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-generator
status:
  conditions:
  - lastTransitionTime: "2026-06-26T15:27:37Z"
    message: recent recommendations were higher than current one, applying the highest
      recent recommendation
    reason: ScaleDownStabilized
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-06-26T15:26:57Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-06-26T15:26:57Z"
    message: the desired replica count is more than the maximum replica count
    reason: TooManyReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 101
        averageValue: 50m
        value: 505m
      name: cpu
    type: Resource
  currentReplicas: 10
  desiredReplicas: 10
