apiVersion: v1
kind: Namespace
metadata:
  name: research-workload
  labels:
    research: autoscaler
---
apiVersion: v1
kind: Namespace
metadata:
  name: research-autoscaler
  labels:
    research: autoscaler
